import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore
import "./globals.css";
import { AppWalletProvider } from "./comp/AppWalletProvider";
import { Navbar } from "./comp/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Puzzle Web3",
  description: "Generated by ace_coderr",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-black`}
      >
        {/* App-wide Solana wallet context */}
        <AppWalletProvider>
          {/* Navbar and page content */}
          <Navbar />
          <main className="min-h-screen">{children}</main>
        </AppWalletProvider>
      </body>
    </html>
  );
}